name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install pre-commit
        run: |
          python -m pip install --user pre-commit
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Run pre-commit on all files
        run: pre-commit run --hook-stage manual --all-files
