name: Create Release

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v1.0.0, v2.1.0, etc.

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Create Release
        uses: softprops/action-gh-release@v2.3.3
        with:
          generate_release_notes: true
